version: '3'
services:
  client:
    build: .
    image: node:20-alpine
    container_name: client
    working_dir: /usr/src
    ports:
      - '3000:3000'
      # Node.jsのデバッグ用のポート開く
      # VSCode上でデバッグしたければ、下記リンクを参考(とりあえずコンソールでいいや)
      # https://ichiki.me/blog/20200113_nextjs_debug
      - '9229:9229'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    tty: true
